name: eventsource
description: A client and server implementation of Server-Sent Events.
version: 0.4.0
homepage: https://github.com/stevenroose/dart-eventsource

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  collection: ^1.19.0
  http: ^1.2.2
  http_parser: ^4.1.0
  logging: ^1.2.0
  sync: ^0.3.0

dev_dependencies:
  test: ^1.25.8
